### ISSUE TITLE
[Suggestion] Potential Field Navigation

### ISSUE THREAD

**Issue by OxMarco** [sarthak268/Obstacle_Avoidance_for_UAV#7]
Looking at the code it seems you are not using any kind of path planning algorithm.
It would be very easy to implement a 2D potential field navigation which could be a starting point for robots moving on a bidimensional space (ASVs).

**Comment by sarthak268** [comment]
Thanks for the suggestion.
Would you like to give this a try?

**Comment by OxMarco** [comment]
Yeah I’m already trying to implement such feature

**Comment by sarthak268** [comment]
Great, Looking forward to your pull request. 

All the best.

**Comment by sarthak268** [comment]
Are you still working on it?

**Comment by OxMarco** [comment]
unfortunately not, I still need to implement the navigating function (only unique minima point).

**Comment by sarthak268** [comment]
Sure, just send a PR once you update some code.
