### ISSUE TITLE
Visualizing with gazebo 

### ISSUE THREAD

**Issue by zpzp307** [sarthak268/Obstacle_Avoidance_for_UAV#8]
Visualizing with gazebo is very straightforward. 
How do you visualize it with a gazebo?

**Comment by sarthak268** [comment]
This repo uses RVIZ for visualization. I think visualization with Gazebo will also be simple. 
You can try to do that, shouldn't take much effort according to me.

**Comment by zpzp307** [comment]
Thank you for your reply.  I am a newbie to ros, then I will try it.


------------------ 原始邮件 ------------------
发件人: "Sarthak Bhagat"<notifications@github.com>;
发送时间: 2019年5月15日(星期三) 晚上10:17
收件人: "sarthak268/Obstacle_Avoidance_For_UAV_"<Obstacle_Avoidance_For_UAV_@noreply.github.com>;
抄送: "。。。"<3186677895@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [sarthak268/Obstacle_Avoidance_For_UAV_] Visualizing with gazebo (#8)




This repo uses RVIZ for visualization. I think visualization with Gazebo will also be simple.
 You can try to do that, shouldn't take much effort according to me.

**Comment by sarthak268** [comment]
Sure, take your time. I am assigning this issue to you. 
You can work on it and then create a pull request.

**Comment by zpzp307** [comment]
Thank you for your enthusiasm, I would like to ask how to install "ardupilot",
"mavros" and "Mission Planner (preferred) or apm planner"

**Comment by sarthak268** [comment]
You can try googling it. They are pretty easy to install.

**Comment by zpzp307** [comment]
Thank you again for your enthusiasm.
I have installed it, but after installing mavros, I tested mavros and entered roslsunch mavros apm2.launch.An error occurred, such as an error in the picture


------------------ 原始邮件 ------------------
发件人: "Sarthak Bhagat"<notifications@github.com>;
发送时间: 2019年5月19日(星期天) 中午11:04
收件人: "sarthak268/Obstacle_Avoidance_For_UAV_"<Obstacle_Avoidance_For_UAV_@noreply.github.com>;
抄送: "。。。"<3186677895@qq.com>;"Assign"<assign@noreply.github.com>;
主题: Re: [sarthak268/Obstacle_Avoidance_For_UAV_] Visualizing with gazebo (#8)




You can try googling it. They are pretty easy to install.

**Comment by sarthak268** [comment]
Send me the error screenshot to my email.

**Comment by zpzp307** [comment]
hello：
      I sent it to your mailbox yesterday, did you receive it?




------------------ 原始邮件 ------------------
发件人: "Sarthak Bhagat"<notifications@github.com>;
发送时间: 2019年5月20日(星期一) 凌晨1:08
收件人: "sarthak268/Obstacle_Avoidance_For_UAV_"<Obstacle_Avoidance_For_UAV_@noreply.github.com>;
抄送: "。。。"<3186677895@qq.com>;"Assign"<assign@noreply.github.com>;
主题: Re: [sarthak268/Obstacle_Avoidance_For_UAV_] Visualizing with gazebo (#8)




Send me the error screenshot to my email.

**Comment by wbzhang233** [comment]
Is this repository totally for global path planning? I would like to make sitl simulation in gazebo and work on vision based real-time obstacle avoidance.

**Comment by sarthak268** [comment]
I think that should be easy, you can visualize any algorithm given you have waypoints, obstacle location, and sizes. You will have to change the way to give waypoints to the algorithm here.
